### ISSUE TITLE
building successfully but failing at last copy step

### ISSUE THREAD

**Issue by fmhc** [micaelmalta/gitian-builder-dogecoin#7]
Hello,
i am running into issues while following your README, after successfully setting it up and then building with  
`/gitian-builder-dogecoin$ ./gitian-build.sh -j 10 -m 12000 --commit --build katzenmalen1.14.4-dev`
i get the following error messages
![image](https://user-images.githubusercontent.com/3387385/126725283-0f601db8-03d9-47c0-9e83-83a771096e4c.png)
What did I miss to set up? how to set up the signer things correctly?

**Comment by micaelmalta** [comment]
@fmhc I fixed some issues and I added some tests to make sur it s building correctly

Also,  on your command `./gitian-build.sh -j 10 -m 12000 --commit --build katzenmalen1.14.4-dev`, you are missing your custom repo URL https://github.com/micaelmalta/gitian-builder-dogecoin#custom-repository

LMK if it works for you!

**Comment by fmhc** [comment]
I had changed the default repo in the file somewhere, i guess. tried multiple times and then gave up because waiting for an hour or so and then not getting any results was a bit frustrating :D 
now with running `./gitian-build.sh -j 8 -m 8192 -u https://github.com/katzenmalen/dogecoin --build katzenmalen 1.14.3` i got results, thanks a lot!
![image](https://user-images.githubusercontent.com/3387385/127328928-cbaa6b2d-e63b-44ba-be6a-89f6546bf3ee.png)
 
![image](https://user-images.githubusercontent.com/3387385/127329209-8ff5ef82-1ea7-4ec4-a89e-428bf7193653.png)

Next question: how can I sign that with my pgp key? you're using mmalta, to what does that refer? filename of your key in a specific folder or repo?

**Comment by micaelmalta** [comment]
Awesome!

@fmhc  Regarding the gpg key, the signer is the name/email of you gpg key. You can follow the gpg doc: https://www.gnupg.org/documentation/manuals/gnupg/Specify-a-User-ID.html

You can have the list of uid doing that command `  gpg --list-keys | grep uid | grep ultimate `

**Comment by fmhc** [comment]
Looks promising, I have tried building my repo now but it fails running `./gitian-build.sh -j 8 -m 8192 -u https://github.com/katzenmalen/dogecoin --commit --build katzenmalen 1.14.4-dev` Guess i have set up the gpg key correctly now, but it still fails.
![image](https://user-images.githubusercontent.com/3387385/127340023-2ba134bd-4ffd-4a14-9130-f5ca3aa31698.png)

the last lines from build.log:
`
ERROR: Feature 'c++1z' was enabled, but the pre-condition 'features.c++14 && tests.c++1z' failed.
make: Leaving directory `/home/ubuntu/build/dogecoin/depends'
make: *** [/home/ubuntu/build/dogecoin/depends/work/build/x86_64-apple-darwin11/qt/5.12.11-4e56e558921/./.stamp_configured] Error 3
`
guess thats a problem on my side with my Qt-Upgrade, i'll dig there further and let it build the dogecoin/dogecoin repo with my sign for another test.

**Comment by fmhc** [comment]
![image](https://user-images.githubusercontent.com/3387385/127379561-17962473-7999-4baf-b46d-768bfab3c39e.png)
looks fine for me, thanks a lot!

**Comment by micaelmalta** [comment]
Awesome! thanks @fmhc for testing it!

**Comment by fmhc** [comment]
Hit me up on Twitter, would love to have a chat with you :)

**Comment by micaelmalta** [comment]
@fmhc Hit me back!
